### ISSUE TITLE
flexibility to allow for element size to differ

### ISSUE THREAD

**Issue by mnikhil-git** [aptinio/text-table#11]
Hi,

the use case for having multiple sub columns with in a single column is failing with the use of text table module. is there a way to allow for element sizes to differ? much similar to having multiple cells with in a single header column?

eg:
irb(main):011:0> t = Text::Table.new :rows => [
irb(main):012:1\*   ['a', 'b'],
irb(main):013:1\*   ['c', 'd'],
irb(main):014:1\*   :separator,
irb(main):015:1\*   ['e', 'f'],
irb(main):016:1\*   :separator,
irb(main):017:1\* ['f', 'k', 'l']
irb(main):018:1> ]

irb(main):020:0> t = Text::Table.new :rows => [
irb(main):021:1\* [['a', 'b'], 'c'],
irb(main):022:1\* ['c', 'd'],
irb(main):023:1\* ]
=> #Text::Table:0x8780e8
irb(main):024:0> puts t
# 

IndexError: element size differs (3 should be 2)
        from /opt/ruby/1.9.3/lib/ruby/gems/1.9.1/gems/text-table-1.2.4/lib/text-table/table.rb:155:in `transpose'
        from /opt/ruby/1.9.3/lib/ruby/gems/1.9.1/gems/text-table-1.2.4/lib/text-table/table.rb:155:in`column_widths'
        from /opt/ruby/1.9.3/lib/ruby/gems/1.9.1/gems/text-table-1.2.4/lib/text-table/table.rb:162:in `separator'
        from /opt/ruby/1.9.3/lib/ruby/gems/1.9.1/gems/text-table-1.2.4/lib/text-table/table.rb:169:in`to_s'
        from (irb):19:in `puts'
        from (irb):19:in`puts'
        from (irb):19
        from /opt/ruby/1.9.3/bin/irb:12:in `<main>'

**Comment by aptinio** [comment]
@mnikhil-git, you make a cell span multiple columns. See: https://github.com/aptinio/text-table#aligning-cells-and-spanning-columns
